hash-format = "sha256"

[[files]]
file = "config/customwindowtitle-client.toml"
hash = "99dad4db591e67b837f3510e3e610f75af08e2b80296196d68d2ddbba6146944"

[[files]]
file = "config/customwindowtitle/icon16.png"
hash = "68573978ef42411ae648e25b7809eb067b93c9193076d0dca551863676876b40"

[[files]]
file = "config/customwindowtitle/icon32.png"
hash = "a7e624d73b9a39f7bf08973e98f455ee22fac90f4c05e9738cf9b8bb9b0e34f1"

[[files]]
file = "config/grass_kiss.json"
hash = "9439f8254146932503037a2e0f82cdbc48a1e9a796ce900e98ee3068b8ec3de6"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "f7b6a500be57ffa0fc17ce4f97f8495bd1c81214c99348ec8dca0815bf2e2640"

[[files]]
file = "config/lithium.properties"
hash = "bf0625692659331c95874a9e644aecf2cac45ea27ba69005e692f2717b5f9947"

[[files]]
file = "config/yosbr/config/armorchroma.json"
hash = "2185170701a680da0ba39c84121ced4f5990cf06f9d79b36f0b7ad1e48f386da"

[[files]]
file = "config/yosbr/config/dark-loading-screen.json"
hash = "34f1a2d445f6d133a5b5f65df1b17c4b175c874020ba95f7d971e61a8cfd68f2"

[[files]]
file = "config/yosbr/config/fastquit-config.txt"
hash = "51737ea18619d5d6f55a8c7aff5ac0375ab8387a68698baa650d4732c8e38df6"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "914ce60745bbe444b7f211bdc1975fb0d52563369492bf65023f66d66f60221f"

[[files]]
file = "config/yosbr/config/lightoverlay.properties"
hash = "94e395e58bd9777c6244a3b443b729df9e51a12d14fc9b4fdb7393bc233f9c2a"

[[files]]
file = "config/yosbr/config/minihud.json"
hash = "4b53eea088523107feec427f95b80a2c0c97f137ddd2f24aadd2541ee6eb6908"

[[files]]
file = "config/yosbr/config/minimalmenu.json"
hash = "251a52ba59008fe14268bf32af1100629f1f054236c8662d831092aa25a3b9e6"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "2a29655cc8ca7470714e32cf6f7416f92777d41f822d4593d037046222a21d55"

[[files]]
file = "config/yosbr/config/roughlyenoughitems/config.json5"
hash = "31797782d867afa0eae5766cc4d5b5019f0054bd8d513331b2c13606a8933af3"

[[files]]
file = "config/yosbr/config/sodium-extra-options.json"
hash = "8f54a898831dd20213f130aeab2339104578d94fb9b6c923f9fb27aae8825dd4"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "ec93565be12fd62f4b9f23d9c2c706968cedc56b022b484918a5dce2d62b569c"

[[files]]
file = "config/yosbr/options.txt"
hash = "0786a0a788cc527ac9ec517abd54b2609627265eca8d261f2b648e1f740996f0"
preserve = true

[[files]]
file = "mods/XaerosWorldMap.jar"
hash = "18014b20bc9ed68c85cfcfb56e7c741d2725dd7468c490fd26ccf990c61c4c81"

[[files]]
file = "mods/advancements-enlarger.pw.toml"
hash = "175be1920d256498fa963fae677cc060c2ff33d6b3f129dd806e7ef130e86506"
metafile = true

[[files]]
file = "mods/animatica.pw.toml"
hash = "b494eb2872c5eb3c498e147be24a62e2c62485e375b9b99c15ae0faf8f9dd2ca"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "fdea52d254e5318fe4884301ca865356ade3f685798548aaa23804b25ff01ca1"
metafile = true

[[files]]
file = "mods/armor-chroma-for-fabric.pw.toml"
hash = "d7b730ba9af222aae704a34891f41497d72620ab75da092714fc4f186d230bcf"
metafile = true

[[files]]
file = "mods/better-anvil.pw.toml"
hash = "39879d1fe072b3ab80cffb44f633386314d40ea2dd81d3226abb6a6f01426622"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
hash = "fa7eed08ecb81a2cc3ec4f9cc5387874936f2496a5739ec71d263a6f26a45c34"
metafile = true

[[files]]
file = "mods/better-resource-pack-sorting.pw.toml"
hash = "8b6a4792d4395eecc90cbdf095a694f503248ac99915e9deb8d6d64f5e6236a1"
metafile = true

[[files]]
file = "mods/boat-item-view.pw.toml"
hash = "aa5edd2c0991a3e43e61bc8c20afc354c9101a328c319af6f2a7682f14764b4c"
metafile = true

[[files]]
file = "mods/bobby.pw.toml"
hash = "33d8e4f2b5e3546f8dd4df0aadcc374b2b1e811f456bdea741dc53b94ac22f11"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "1d5ff51cdf133abc091eda828043e7f4472bba1faea1faacc41bb50ca8315b28"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "208b6e7574b7a5fee941b90257e34cb6a4ddbb162ee16ff475d030e39fd5e042"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
hash = "0da3b33d0d62fcaf24835fb432b8dd9be02e82897cd43fddc38fa81106203d37"
metafile = true

[[files]]
file = "mods/clickthrough.pw.toml"
hash = "1a4c9d83b0709fd2f91814eb67f81e19bb1493315c42cb65efe911d0f34c5a13"
metafile = true

[[files]]
file = "mods/client-paintings.pw.toml"
hash = "e754691346157f71db56e3c3dbd2ce8e09d05536e40b0a2c1f84037d51e549a9"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "213cad77d46ff46fe20780b01856cb1a8812747e9c3564203669bf3905e646e2"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "984741a3b4d5612df37b81d7349dd1f130257eaf7d94d95b72ce43fff9411885"
metafile = true

[[files]]
file = "mods/custom-window-title.toml"
hash = "6670c459d79e48e809d6f3b7fb4e494e71c8ce7d63b9c522d46702467d272748"
metafile = true

[[files]]
file = "mods/dark-loading-screen.pw.toml"
hash = "ee791485dbd1008c51079c693960b6555311d2fc44d2a4901b7f4455d00eea24"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "783c0415795fc4bea6d85315aac54d3a3f2770fcd02d66dad1f626b311f8bf4f"
metafile = true

[[files]]
file = "mods/e4mc.pw.toml"
hash = "97a3facf4a7a210480038f11399f29808b3a8237668ac03fc90eb8e6dba6bda2"
metafile = true

[[files]]
file = "mods/eating-animation.pw.toml"
hash = "92f796bb39c6235298ccf33b64505923870bc3a258cbb2114d0ec036bfe18b6d"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "bf886d03a194a4036f02afe690cb21ca346fff20f4193355994ec97f046a8809"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "ca9a7c2cf85d33a348227cc025b6edc1341bc846f2005ee87d626763112b9eec"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "7873ca5fa00f1d5bcc11ba839aed4866e660017f8caee9337c7dffc8682d5653"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "7be1e122e9ef8f1b7f2df9ffccf02cf83a52d0a53ae5ba7d07ea7bd3cc149101"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "32cff441dba71cee026356fe08147e289183532b7215071cdb0dd91af56aa643"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "f25e49ca19098f7488d30092719c0a8e480da5f01b6e7069bf1093fea82c80a8"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "98da553a1ba2d41bfce3585198641c2d927c702d5403ebec82402ae51ddf707f"
metafile = true

[[files]]
file = "mods/grass-kiss.pw.toml"
hash = "85d7e2120286264565ce652bd87417565d4ed1e5101375d047e512943eac5a73"
metafile = true

[[files]]
file = "mods/here-be-no-dragons.pw.toml"
hash = "d7d04009eba5c1068bd9aa5214c7ef87dcf426c4f23229b3dbfa6996952fd7c5"
metafile = true

[[files]]
file = "mods/hidenbt-1.1.0.jar"
hash = "98fdccb534eb9f2bd38587e4d23a4c7e9cebeb9f768658bc91b44c10c36d1c3c"

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "fd0d31c123f53fb70d79e3ac5333dc9178b378c87d46eb0b8f63db324f67fe51"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "e8168531c092676d47cac3657bfc525f096f11ff5372ce6e322ad57778b81635"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "ec644a70524673946d8a987bbc4d3f0968c4885f55541b837ee14a366b218d35"
metafile = true

[[files]]
file = "mods/lava-clear-view-fabric.pw.toml"
hash = "649a44643b593d49c91ead5d89a1d0f90698e1ca87fa262b95ef52053e189e66"
metafile = true

[[files]]
file = "mods/light-overlay.pw.toml"
hash = "54037e4122f477f500dc3002b2f0ab9cda99d0fceb70da1d163be1afc99ec060"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "54a337d13450b35dfc931e7a5f3ed9fca1a1992ec51d3b1e4ea1cb5f7cd2d09c"
metafile = true

[[files]]
file = "mods/main-menu-credits.pw.toml"
hash = "1527caee4fc4f26b525a41a95dd07dae21ab3c8d2c391237c79396abf7e9b2d7"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "3926d859126491c673d921c3f3f93316766689ff0694f83d82255ec4776d3c74"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "4ce761e594c255a802bd4b0b4b6312e740130b17d77764c389cef4c8417ae8af"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "ec2e01258ac91cd8a753b776bfe1e01ad7dacfedbbff19fb4eec779bb10cf4aa"
metafile = true

[[files]]
file = "mods/minimal-menu.pw.toml"
hash = "28e3b2cd3c3146779d9783ee807aa34cd79f0cdc839e811cc68b5a208cfa4977"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "b89656eaf7e4404d8d2c5b1e1155aae85a839939f83cab6d1b5e791412ad5f86"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "9d903fdb128e98639fca7b110c1d1993bfaddc9025ccbe0d03753c429f895134"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "be0fd8b9cd9f8a94428ea8ac5ec84f4f7bab23697236b7a2e54d8537834e0315"
metafile = true

[[files]]
file = "mods/monsters-in-the-closet.pw.toml"
hash = "63914b645092557cf4824cf3be35e71f5cf8b9345a1c45de27d5da13e97b48f4"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "631a4aeea3ca16afe689e67c409cb39d18af269e1eecd944d042a85a88d34314"
metafile = true

[[files]]
file = "mods/no-telemetry.pw.toml"
hash = "5f9870a1b70f585f7ca5ca97d5369056f6f6ab84d9897a35b545b0311e69c213"
metafile = true

[[files]]
file = "mods/originaddons.pw.toml"
hash = "591da12ccba0d54b7a853947c5ce4e5e7135ac8991bf210904a58ad1c771f46e"
metafile = true

[[files]]
file = "mods/origins-enhanced.pw.toml"
hash = "83eecd0577e1b709c8eeb1986454a16fce911e5f3dcc3a4c8d65636f7ea63f0b"
metafile = true

[[files]]
file = "mods/randomblockplacement.pw.toml"
hash = "6cafffa10b7b27aa2f32af2268e47b2a5e51f33e6935ab1ecdfa8106fe4cdc12"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "b2e3be698473bfb3f08865a11e74c9ee8d47239ac72a79d60acc1ee381722a50"
metafile = true

[[files]]
file = "mods/rei.pw.toml"
hash = "f37d98015547fa4c5c392eec612376bebf6af9ed83cde466938bebf60c7ab68d"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "06e8d589fbff47c4724c1c0e59b73ca1e87d65e75e7ea7c77bfee11fa3d8c7aa"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "8da0d4c285e7e57aee3f08ab4e268d04518704ace4060744f042aef3a7f6bc50"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "aa4dcf55ac3191b0b31437521714c1d28364c3396cf06ef07fa76a08488c1837"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "2aeab4f3b0a720ed02f400d9b521f1858474d4f8f7c3577ce916d5aa31fe37e1"
metafile = true

[[files]]
file = "mods/wavey-capes.pw.toml"
hash = "8a4a4e24b30d401e195211153879287b4e2bb1bbb3e56d904ca84bffbecd7f99"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "80bab11e8d1438ec93695050f087dc2f9d0ae1d2523a17b8236af7029f14119e"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "7c2712882baa2ed177b9b961cc1052b857f11ed1455609f9e9f01332c0317f12"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "df9929f0a90f0c54a870ed182c0543ce579d07b84089d2fec6131917c53b5bab"
metafile = true

[[files]]
file = "resourcepacks/VanillaTweaks.zip"
hash = "f0f6d7422bfd2737dfff0a43218f6ff73a7aadf83aac9fd83fbadde564dffb6d"

[[files]]
file = "resourcepacks/andos-pack.zip"
hash = "4808c8c7ae2455b43fb7571995bfd0b70a1c5dc9518e3c96ef787e0961e23960"

[[files]]
file = "resourcepacks/pollocraft.zip"
hash = "ed4d534c33b2d7eb2499cfa2483aee76aab1e6043d116b279f2fc004947338df"

[[files]]
file = "shaderpacks/ComplementaryShaders_v4.7.1.zip.txt"
hash = "b5b710827d05726a6f8297ee5a1293147006ef56e9d61edcd6910fa2b774e012"

[[files]]
file = "shaderpacks/complementary-shaders-v4.pw.toml"
hash = "d468216fa4b4917769fae3179b7bb47656f8a65474e87352d5b379783384e0af"
metafile = true
